### ISSUE TITLE
Integrate with Sarif and publish to Github Security tab

### ISSUE THREAD

**Issue by sandeshRazorpay** [Ynniss/golang-security-action#5]
Can we make this action return a Sarif output and upload the results to Github's Security tab? That would make life really easy! 

nodejsscan can do something similar, would be great to have that for gosec too

**Comment by Ynniss** [comment]
Hi, thanks for your feedback

Issue pinned !
i'll handle this in few weeks, won't work on it for now
If you want to begin working on it ,  feel free to contribute 👌🏽

**Comment by erzz** [comment]
I am willing to try and help - the biggest hurdle is creating a good project with a variety of issues to test against.  If anyone has a good example project in this regard then I can play around with it

**Comment by Ynniss** [comment]
Hi ! 

Good to know :)

Feel free to work on this github action, it's completely open source.
It's indeed pretty basic yet, and i haven't came back to it yet, lots of improvements are possible.

I guess you could test with this project https://github.com/palantir/go-baseapp

or something pretty popular like this one => https://github.com/gothinkster/golang-gin-realworld-example-app

**Comment by erzz** [comment]
Nice example projects

Just as I sat down to start looking into it - I find they just release sarif support out of the box

Tested it and works well

```
- name: Run Gosec Security Scanner
  uses: securego/gosec@master
  with:
    args: "-no-fail -fmt sarif -out results.sarif -conf .gosec-config.json ./..."
- name: Upload SARIF file
     uses: github/codeql-action/upload-sarif@v1
       if: always()
       with:
         sarif_file: results.sarif
```
